application: praisebeer
version: 1
runtime: python
api_version: 1

handlers:
- url: /upclookup
  script: upcLookup.py
- url: /namelookup
  script: nameLookup.py
- url: /cron
  script: cron.py
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /flushDataStore
  script: flushDataStore.py
  login: admin
- url: /flushMemcache
  script: flushMemcache.py
  login: admin
- url: /dataViewer
  script: dataViewer.py
  login: admin              
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin  