application: praisebeer
version: 1
runtime: python
api_version: 1

handlers:
- url: /upclookup
  script: upcLookup.py
- url: /namelookup
  script: nameLookup.py
- url: /populateUPCs
  script: populateUPCs.py
- url: /cron
  script: cron.py
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  